abilities:
    bomber:
        reload: true
        reloadTime: 15
    confuser:
        reload: true
        reloadTime: 15
    effector:
        reload: true
        reloadTime: 15
    hook:
        reload: true
        reloadTime: 15
    missile:
        reload: true
        reloadTime: 15
    scatter:
        reload: true
        reloadTime: 15
        arrowsSet: 2
    trail:
        reload: true
        reloadTime: 15
        removeFire: true
        removeFireAfter: 15