name: stuntguy3000-t1
main: com.tenjava.entries.stuntguy3000.t1.FireFlight
version: '${project.version}'
author: stuntguy3000
commands:
    FireFlight:
        description: Main command for FireFlight
        aliases: [ff, firef]